[[redirects]]
from = "/api/*"
to = "https://api.mapbox.com/:splat?access_token=TOKEN_PLACERHOLDER"
status = 200
headers = { Referer = "https://off-grid-calculator.netlify.app/" }
force = true

[build]
command = "sed -i \"s|TOKEN_PLACERHOLDER|${MAPBOX_TOKEN}|g\" netlify.toml"